### ISSUE TITLE
[BUG] @position-try can't be used by multiple selectors

### ISSUE THREAD

**Issue by jamesnw** [oddbird/css-anchor-positioning#233]
**Describe the bug**
As introduced in #202, multiple selectors for a single position-try-fallbacks rule that uses an at position try rule is not supported.

```css
#targetA, #targetB{
  position-try-fallbacks: --my-at-rule;
}
```

Only 1 fallback will be made, but the at rule will apply to  `#targetA` and `#targetB` differently.
