### ISSUE TITLE
[BUG] CSS imports not working with 0.5.1

### ISSUE THREAD

**Issue by lhansford** [oddbird/css-anchor-positioning#314]
**Describe the bug**
I have a CSS file that imports another CSS file. When the polyfill is enabled the imported styles stop working. I rolled back to 0.5.0 and it started working again.

**To Reproduce**
```css
@import url('./typography.css');

p {
  color: black;
}
```

typography.css: 
```css
p {
  color: red;
}
```

The second stylesheet will load but not be applied.

**Browsers tested on**
Firefox 137 on Mac
